@startuml name
title シーケンス図: LINE, Apple, Googleログイン with Firebase Auth and UserID

actor ユーザー
participant アプリ
participant function
participant "LINE SDK" as LINE_SDK
participant "LINE Platform" as LINE_Platform
participant "Apple" as Apple
participant "Google" as Google
participant Firebase Authentication
participant データベース

== LINE Login ==
ユーザー -> アプリ: LINEでログイン
アプリ -> LINE_SDK: ログイン
LINE_SDK --> アプリ: success(accessToken)
アプリ -> function: accessToken
function -> LINE_Platform: GET /oauth2/v2.1/verify (accessToken)
LINE_Platform --> function: success(client_id, expires_in)
function -> LINE_Platform: GET /v2/profile (accessToken)
LINE_Platform --> function: success(lineUserId, name, imageUrl)
' TODO: もっと詳しく
function -> Firebase Authentication: アカウント検索・登録(lineUserId)
' TODO: userIDを変更
Firebase Authentication --> function: success(userID)
function --> アプリ: success(userID)
アプリ --> ユーザー: ログイン成功
@enduml